version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cnr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cnr_tp
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cnr-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cnr-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: cnr_tp
    volumes:
      - ./excel_data:/app/excel_data
    networks:
      - cnr-network

  frontend:
    build:
      context: ./frontend/cnr
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  cnr-network:
    driver: bridge

volumes:
  mysql_data:
  excel_data: 