version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cnr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cnr-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cnr-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - cnr-network

  frontend:
    build:
      context: ./frontend/cnr
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  cnr-network:
    driver: bridge

volumes:
  mysql_data: 