interface WilayaData {
  value: number;
  color: string;
}

type WilayaMap = {
  [key: string]: WilayaData;
};

export const data: WilayaMap = {
  Adrar: { value: 1, color: "#fff9eb" },
  Chlef: { value: 2, color: "#ebf0f9" },
  Laghouat: { value: 3, color: "#f0ebf9" },
  "Oum El Bouaghi": { value: 4, color: "#f9ebf1" },
  Batna: { value: 5, color: "#ebf9ee" },
  Béjaïa: { value: 6, color: "#f9f0eb" },
  Biskra: { value: 7, color: "#ebf9f2" },
  Béchar: { value: 8, color: "#f0fff9" },
  Blida: { value: 9, color: "#f9f4eb" },
  Bouira: { value: 10, color: "#ebf4f9" },
  Tamanrasset: { value: 11, color: "#f4ebf9" },
  Tébessa: { value: 12, color: "#f9ebeb" },
  Tlemcen: { value: 13, color: "#f9fff0" },
  Tiaret: { value: 14, color: "#e5f9eb" },
  "Tizi Ouzou": { value: 15, color: "#ebf9f7" },
  Alger: { value: 16, color: "#ebf9ee" },
  Djelfa: { value: 17, color: "#ebf9ff" },
  Jijel: { value: 18, color: "#f2f9eb" },
  Sétif: { value: 19, color: "#f9ebf5" },
  Saïda: { value: 20, color: "#f9fff9" },
  Skikda: { value: 21, color: "#ebf0f0" },
  "Sidi Bel Abbès": { value: 22, color: "#ebf9eb" },
  Annaba: { value: 23, color: "#f0ebeb" },
  Guelma: { value: 24, color: "#fff0eb" },
  Constantine: { value: 25, color: "#ebf9f4" },
  Médéa: { value: 26, color: "#ebf3f9" },
  Mostaganem: { value: 27, color: "#f0ebf0" },
  "M'Sila": { value: 28, color: "#f9ebf9" },
  Mascara: { value: 29, color: "#ebf9e5" },
  Ouargla: { value: 30, color: "#ebfff9" },
  Oran: { value: 31, color: "#ebebf9" },
  "El Bayadh": { value: 32, color: "#f9ebeb" },
  Illizi: { value: 33, color: "#f9f9eb" },
  "Bordj Bou Arréridj": { value: 34, color: "#f4f9eb" },
  Boumerdès: { value: 35, color: "#ebebf0" },
  "El Tarf": { value: 36, color: "#f9ebf2" },
  Tindouf: { value: 37, color: "#fff9eb" },
  Tissemsilt: { value: 38, color: "#ebf9e0" },
  "El Oued": { value: 39, color: "#f9ebff" },
  Khenchela: { value: 40, color: "#ebf0eb" },
  "Souk Ahras": { value: 41, color: "#ebfff0" },
  Tipaza: { value: 42, color: "#f0ebf5" },
  Mila: { value: 43, color: "#f9f9f0" },
  "Aïn Defla": { value: 44, color: "#f9f0eb" },
  Naâma: { value: 45, color: "#ebf5f9" },
  "Aïn Témouchent": { value: 46, color: "#f9ebf0" },
  Ghardaïa: { value: 47, color: "#f9f0f0" },
  Relizane: { value: 48, color: "#ebf0f9" },
  "El M\\'ghair": { value: 49, color: "#f9f9eb" },
  "El Menia": { value: 50, color: "#ebf0f0" },
  "Ouled Djellal": { value: 51, color: "#f9ebeb" },
  "Bordj Badji Mokhtar": { value: 52, color: "#f0f9eb" },
  "Béni Abbès": { value: 53, color: "#ebebeb" },
  Timimoun: { value: 54, color: "#f9f0eb" },
  Touggourt: { value: 55, color: "#f4ebf9" },
  Djanet: { value: 56, color: "#ebf9f9" },
  "In Salah": { value: 57, color: "#f9f9f9" },
  "In Guezzam": { value: 58, color: "#ebebf9" },
};
